
[api]
  Address = "/ip4/0.0.0.0/tcp/39812"

[db]
  type = "mysql"

  [db.mysql]
    connMaxLifeTime = "1m0s"
    connectionString = "root:Root1234@(127.0.0.1:3306)/messager?parseTime=true&loc=Local"
    debug = false
    maxIdleConn = 10
    maxOpenConn = 10

  [db.sqlite]
    debug = false
    path = "./message.db"

[jwt]
  url = "http://127.0.0.1:8989"

[log]
  level = "info"
  path = "messager.log"

[messageService]
  skipProcessHead = false
  skipPushMessage = false
  tipsetFilePath = "./tipset.json"

[messageState]
  CleanupInterval = 86400
  DefaultExpiration = 259200
  backTime = 86400

[node]
  token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.S5ucwvhFM6tkuLInwZi0VSBEl1T570oLVfp47KBWcXo"
  url = "/ip4/127.0.0.1/tcp/3453"

[wallet]
  scanInterval = 10
