
[MessageService]
  tipsetFilePath = "./tipset.db"

[MessageState]
  CleanupInterval = "86.4µs"
  DefaultExpiration = "259.2µs"
  backTime = "86.4µs"

[address]
  remoteWalletSweepInterval = "10ns"

[api]
  Address = "127.0.0.1:39812"

[db]
  type = "sqlite"

  [db.mysql]
    addr = ""
    connMaxLifeTime = "0s"
    maxIdleConn = 0
    maxOpenConn = 0
    name = ""
    pass = ""
    user = ""

  [db.sqlite]
    path = "./message.db"

[jwt]
  expireDuration = "0s"
  secret = ""

[log]
  path = "messager.log"

[node]
  url=   "/ip4/192.168.1.134/tcp/3453"
  token= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.n0eSFUWCbosjteqktQOcOghw7VWOm5wODkgpoT2yFJw"

