
[address]
  remoteWalletSweepInterval = 10

[api]
  Address = "127.0.0.1:39812"

[db]
  type = "sqlite"

  [db.mysql]
    addr = ""
    connMaxLifeTime = "0s"
    maxIdleConn = 0
    maxOpenConn = 0
    name = ""
    pass = ""
    user = ""

  [db.sqlite]
    path = "./message.db"
    debug = false

[jwt]
  expireDuration = "0s"
  secret = ""

[log]
  path = "messager.log"

[messageService]
  isProcessHead = true
  tipsetFilePath = "./tipset.txt"

[messageState]
  CleanupInterval = 86400
  DefaultExpiration = 259200
  backTime = 86400

[node]
    url = "/ip4/127.0.0.1/tcp/3453"
    token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.8dSWe7S53eF1Ue6XfYUUN-vPSfUWL12xyWkOJv6DNks"
#  url=   "/ip4/127.0.0.1/tcp/3453"
#  token= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.S5ucwvhFM6tkuLInwZi0VSBEl1T570oLVfp47KBWcXo"
