
[MessageService]
  tipsetFilePath = "./tipset.db"

[MessageState]
  CleanupInterval = "24h0m0s"
  DefaultExpiration = "72h0m0s"
  backTime = "24h0m0s"

[address]
  remoteWalletSweepInterval = "10s"

[api]
  Address = "127.0.0.1:39812"

[db]
  type = "sqlite"

  [db.mysql]
    addr = ""
    connMaxLifeTime = "0s"
    maxIdleConn = 0
    maxOpenConn = 0
    name = ""
    pass = ""
    user = ""

  [db.sqlite]
    path = "./message.db"

[jwt]
  expireDuration = "0s"
  secret = ""

[log]
  path = "messager.log"

[node]
  token = ""
  url = ""
