
[api]
  Address = "0.0.0.0:39812"

[db]
  type = "sqlite"

  [db.mysql]
    addr = ""
    connMaxLifeTime = "0s"
    debug = false
    maxIdleConn = 0
    maxOpenConn = 0
    name = ""
    pass = ""
    user = ""

  [db.sqlite]
    debug = false
    path = "./message.db"

[jwt]
  url = "http://127.0.0.1:8989"

[log]
  path = "messager.log"
  level = "info"  # log level: trace debug info warn|warning error fatal panic

[messageService]
  skipProcessHead = false
  skipPushMessage = false
  tipsetFilePath = "./tipset.json"

[messageState]
  CleanupInterval = 86400
  DefaultExpiration = 259200
  backTime = 86400

[node]
#  url = "/ip4/8.130.165.167/tcp/3453"
#  token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.R6UZS9i6Y9vqAF-O4Z6y74uDK_8jT0M7OzqrrbNQ3II"
  url = "/ip4/127.0.0.1/tcp/3453"
  token= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.S5ucwvhFM6tkuLInwZi0VSBEl1T570oLVfp47KBWcXo"

[wallet]
  scanInterval = 10
