
[address]
  localWalletSweepInterval = "120ns"
  remoteWalletSweepInterval = "10ns"

[api]
  Address = "127.0.0.1:39812"

[db]
  type = "sqlite"

  [db.mysql]
    addr = ""
    connMaxLifeTime = "0s"
    maxIdleConn = 0
    maxOpenConn = 0
    name = ""
    pass = ""
    user = ""

  [db.sqlite]
    path = "./message.db"

[jwt]
  expireDuration = "0s"
  secret = ""

[log]
  path = "messager.log"

[node]
  token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJhbGwiXX0.50-NxTSm90nOzY5bu9XUc49Rk7k2iW7PlHb9BvErDpM"
  url = "/ip4/127.0.0.1/tcp/3453"
