
[BatchReplace]
  BlockTime = "5m"
  From = ""

  [[BatchReplace.Selectors]]
    ActorCode = ""
    Methods = [5]

[Messager]
  Token = ""
  URL = "/ip4/127.0.0.1/tcp/39812"

[Venus]
  Token = ""
  URL = "/ip4/127.0.0.1/tcp/3453"
